steps:
  # 1. Build et push de l'image web
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}']
  
  # # 2. Créer le bucket Cloud Storage pour la base de données (si nécessaire)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['storage', 'buckets', 'create', 'gs://${PROJECT_ID}-database', '--location=${_REGION}', '--uniform-bucket-level-access', '--public-access-prevention']
  #   id: 'create-bucket'
  #   allowFailure: true
  
  # # 3. Copier la base de données dans le bucket
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['cp', 'database.db', 'gs://${PROJECT_ID}-database/']
  #   allowFailure: true
  
  # 4. Déployer le service web sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fictional-universe-web'
      - '--image=${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=8Gi'
      - '--cpu=8'
      - '--min-instances=0'
      - '--max-instances=4'
      - '--set-env-vars=DB_PATH=/tmp/database.db,OLLAMA_HOST=http://34.77.137.161:11434,CUSTOM_LLM_URL=${_CUSTOM_LLM_URL}'
      - '--set-cloudsql-instances=${PROJECT_ID}:${_REGION}:fictional-universe-sql'
      - '--add-volume=name=db-volume,type=cloud-storage,bucket=${PROJECT_ID}-database'
      - '--add-volume-mount=volume=db-volume,mount-path=/tmp'


  # 6. Configurer VPC connector pour permettre la communication entre services
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'services'
  #     - 'update'
  #     - 'fictional-universe-web'
  #     - '--region=${_REGION}'
  #     - '--vpc-connector=${_VPC_CONNECTOR}'
  #     - '--add-cloud-sql-instances=${PROJECT_ID}:${_REGION}:fictional-universe-sql'

substitutions:
  _REGION: europe-west1
  _REPOSITORY: fictional-universe
  _TAG: latest
  _CUSTOM_LLM_URL: http://90.16.29.83:8000/
  # _VPC_CONNECTOR: fict-univ-con

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/web:${_TAG}'